#!/bin/sh
set -o errexit
echo -n 'version (do not add v): '
read VERSION
echo -n 'min core version: '
read MINIMUM_CORE_VERSION
echo -n 'verified core version: '
read VERIFIED_CORE_VERSION
cat >module.json <<EOF
{
    "id" : "lang-sv",
    "title" : "Swedish [Core] - Foundry på svenska",
    "version" : "$VERSION",
    "compatibility": {
        "minimum": "$MINIMUM_CORE_VERSION",
        "verified": "$VERIFIED_CORE_VERSION"
    },
    "author" : "xdy",
    "description" : "Swedish language support for Foundry VTT - Foundry på svenska",
    "coreTranslation": true,
    "languages" : [
      {
         "lang" : "sv",
         "name" : "Svenska",
         "path" : "sv.json"
      }
    ],
    "packs" : [],
    "scripts" : [],
    "styles" : [],
    "url" : "https://github.com/xdy/foundryvtt-lang-sv",
    "manifest" : "https://raw.githubusercontent.com/xdy/foundryvtt-lang-sv/master/module.json",
    "download" : "https://github.com/xdy/foundryvtt-lang-sv/archive/v$VERSION.zip",
    "authors": [
      {
        "name": "Jonas Karlsson",
        "url": "https://gnu.xdy.se/home",
        "discord": "xdy#3735",
        "twitter": "@xdy",
        "reddit": "u/xdydxy"
      }
    ],
  "media": [
    {
      "type": "icon",
      "url": "https://raw.githubusercontent.com/xdy/foundryvtt-lang-sv/master/foundry_lang_sv.svg",
      "loop": false,
      "flags": {}
    },
    {
      "type": "cover",
      "url": "https://raw.githubusercontent.com/xdy/foundryvtt-lang-sv/master/foundry_lang_sv.svg",
      "loop": false,
      "flags": {}
    },
    {
      "type": "setup",
      "caption": "Foundry på Svenska",
      "thumbnail": "/modules/lang-sv/foundry_lang_sv.svg",
      "loop": false,
      "flags": {}
    }
  ],
  "flags": {
    "media": [
      {
        "type": "cover",
        "url": "https://raw.githubusercontent.com/xdy/foundryvtt-lang-sv/master/foundry_lang_sv.svg"
      }
    ],
    "manifestPlusVersion": "1.2.0",
    "allowBugReporter": true
  }
}
EOF
git add --all
git commit -m "Released version $VERSION"
git tag --force "v$VERSION"
git push --tags --force
git push
