#!/bin/sh
set -o errexit
echo -n 'version: '
read VERSION
echo -n 'min core version: '
read MINIMUM_CORE_VERSION
echo -n 'max core version: '
read COMPATIBLE_CORE_VERSION
cat >module.json <<EOF
{
    "name" : "lang-sv",
    "title" : "Swedish [Core]",
    "version" : "$VERSION",
    "minimumCoreVersion" : "$MINIMUM_CORE_VERSION",
    "compatibleCoreVersion" : "$COMPATIBLE_CORE_VERSION",
    "author" : "xdy",
    "description" : "Swedish language support for Foundry VTT",
    "coreTranslation": true,
    "languages" : [
      {
         "lang" : "sv",
         "name" : "Svenska",
         "path" : "sv.json"
      }
    ],
    "packs" : [],
    "scripts" : [],
    "styles" : [],
    "url" : "https://github.com/xdy/foundryvtt-lang-sv",
    "manifest" : "https://raw.githubusercontent.com/xdy/foundryvtt-lang-sv/master/module.json",
    "download" : "https://github.com/xdy/foundryvtt-lang-sv/archive/v$VERSION.zip",
    "manifestPlusVersion": "1.0.0",
    "authors": [
      {
        "name": "Jonas Karlsson",
        "url": "https://gnu.xdy.se/home",
        "discord": "xdy#3735",
        "twitter": "@xdy",
        "reddit": "u/xdydxy"
      }
    ],
    "media": [
      {
        "type": "icon",
        "url": "https://raw.githubusercontent.com/xdy/foundryvtt-lang-sv/master/foundry_lang_sv.svg"
      },
      {
        "type": "cover",
        "url": "https://raw.githubusercontent.com/xdy/foundryvtt-lang-sv/master/foundry_lang_sv.svg"
      }
    ]
}
EOF
git add --all
git commit -m "Released version $VERSION"
git tag --force "v$VERSION"
git push --tags --force
git push